{% set name = "sqlalchemy-vertica-python" %}
{% set version = "0.5.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sqlalchemy-vertica-python-{{ version }}.tar.gz
  sha256: 993c5fa3ed7ac0c8475de73ddb751271ba1515a402ede523cc58ee12ea47cf83

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - vertica-python

test:
  imports:
    - sqla_vertica_python
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bluelabsio/sqlalchemy-vertica-python
  summary: Vertica dialect for sqlalchemy using vertica_python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - FernandezMathieu
